server:
  port: 8777
spring:
  datasource:
    initialization-mode: never
    password: root1234
    url: jdbc:mysql://localhost:3306/notification_bitgo?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true